[package]
name = "actix-jwt"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
chrono = "0.4.40"
dotenv = "0.15.0"
env_logger = "0.11.8"
jsonwebtoken = "9.3.1"
scalar-doc = { version = "0.1.2", features = ["actix"] }
serde = { version = "1.0.219", features = ["derive"] }
